services:
   backend:
     build: ./backend
     container_name: bookdevops-backend
     ports:
       - "7001:7001"
     environment: 
       - FLASK_ENV=development
     restart: unless-stopped
     networks:
       - bookdev-network
   frontend:
     build: ./frontend
     container_name: bookdevops-frontend
     ports:
       - "7000:5173"
     depends_on:
       - backend 
     restart: unless-stopped
     networks:
       - bookdev-network
networks:
  bookdev-network:
    driver: bridge
