apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: bookish
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: hophopp/bookdev-backend:latest
          ports:
            - containerPort: 7001
          env:
            - name: FLASK_ENV
              value: development
